### PR TITLE
Improved performance for .NET 9.0+ using the new System.Threading.Lock.

### PR DESCRIPTION
**Pull request by MarkCiliaVincenti**
Before submitting this pull request I have...
- [X] read EPPlus Softwares [Contribution Guidlines](CONTRIBUTING.md)
- [X] ensured that the functionality I have added/changed is covered by new unit tests.
- [X] merged the target branch into the PR branch and resolved any merge conflicts
- [X] Run all the unit tests and ensured that they all are green (unless the purpose of the PR is to provide us with failing unit tests).

### CODE REVIEW

**Comment by JanKallman** [comment]
.NET 9 is still in preview, so we will not look at this pr now.

**Comment by MarkCiliaVincenti** [comment]
Sure, once .NET 9 is released in November, all that would be needed here is to change back LangVersion from preview to latest and fix any merge conflicts.

**Comment by JanKallman** [comment]
I'll close this pr, as we cannot implement it now and it's non-mergeable. We will look at this when .NET 9  has been released. See #1611

**Comment by MarkCiliaVincenti** [comment]
@JanKallman a new version of Backport.System.Threading.Lock has come out that acts as a source generator and basically dropping the DLL as a dependency. If this new development makes you reconsider, I will amend this PR accordingly.

**Pull request closed without merging**
