### PR TITLE
#779 implemented FullPrecision workbook property

### PR DESCRIPTION
**Pull request by ihorbach**

### CODE REVIEW

**Comment by swmal** [comment]
Hi,

Thanks for this PR. We will keep it as an enhancement request. Our concern with the suggested solution is that it would have a negative performance impact on the overall EPPlus functionality.  The `SetValueInner` function can be called an enormous amont of times when creating larger workbooks and this would introduce Xml DOM access and use of regular expressions into this function.

**Review by kangzixiang — APPROVED** [review]

**Comment by ashahabov** [comment]
Hello,

is there some updates regard this feature? Is there already implemented in the latest version?

**Comment by swmal** [comment]
@ashahabov, @ihorbach 

I am closing this PR, partly due to the concerns in my comment above. We will however have a deeper look at this as we believe it is a valueable feature that EPPlus currently is missing and we also have a "high level thought" on how it should be implemented. This feature request will live on in our [Epics project](https://github.com/orgs/EPPlusSoftware/projects/2?pane=issue&itemId=61080050).

**Comment by ashahabov** [comment]
@swmal, thank you for the quick reply.

**Pull request closed without merging**
