### PR TITLE
Memoize measurestring

### PR DESCRIPTION
**Pull request by simendsjo**
- Note that this builds on top of another PR I have added (see first commit).
- Note that string hash collisions might generate wrong result in some cases. Is this acceptable?
- I didn't implement this for net35 as it didn't include Tuple.
- Used Tuple rather than ValueTuple for netframework as the project doesn't reference ValueTuple (should it?)
- If ValueTuple is included, the implementation would be simpler (and faster for netframework)

### CODE REVIEW

**Comment by simendsjo** [comment]
I notice it fails a test:
```
  Failed OpenAndReadExternalLinkDdeOle [25 ms]
  Error Message:
   Assert.IsNotNull failed. 
  Stack Trace:
     at EPPlusTest.Core.ExternalLinksTest.OpenAndReadExternalLinkDdeOle() in C:\projects\epplus\src\EPPlusTest\Core\ExternalReferenceTest.cs:line 258
```

Flaky test, or is it my fault?

**Comment by JanKallman** [comment]
Hello,
Good idea.
Instead of the Tulple, it might be faster to use a long or ulong for the key.
Something like this:
`((ulong)int1) | (((ulong)int2) << 31)`
This will work in 3.5 as well.
Hash collisions must be very rare, so I cant see that it's a problem.

BTW, are you willing to sign our CAA?, See https://github.com/EPPlusSoftware/EPPlus/blob/develop/CONTRIBUTING.md.
You are close to the 20 lines of code where we require this, if you are interested in making additional PR's.

**Comment by simendsjo** [comment]
>  Instead of the Tulple, it might be faster to use a long or ulong for the key.

Nice observation. I packed the two ints in an ulong.

> BTW, are you willing to sign our CAA?

Done

**Comment by JanKallman** [comment]
Thanks :)

**Pull request merged**
