### PR TITLE
Bug/empty relid fix

### PR DESCRIPTION
**Pull request by rdhasse**
For the workbook I have, the relId is empty and an exception occurs when the below line executes.

pck.Workbook.Part.GetRelationship(relId); 

#120

### CODE REVIEW

**Comment by JanKallman** [comment]
Thanks, I'll apply the fix.
Just a qustion so I understand the problem. 
What kind of worksheet is this that don't contain a relId? Can you supply the xml for workbook?

**Comment by rdhasse** [comment]
The original workbook was a *.xlsm.  I converted *.xlsx hoping it would resolve the issue, but it still occurred.
If you want to know other details about the type of workbook let me know how to find that information and I'll send it.
I can't provide the workbook as it contains sensitive financial data.
    On Friday, June 12, 2020, 03:56:48 AM CDT, Jan Källman <notifications@github.com> wrote:  
 
 


Thanks, I'll apply the fix.
Just a qustion so I understand the problem.
What kind of worksheet is this that don't contain a relId? Can you supply the xml for workbook?

**Comment by JanKallman** [comment]
The workbook is a zip package , so rename the .xlsx file .zip. Then I would be interested in the xl\workbook.xml inside the package that contains the list of worksheets.

**Comment by rdhasse** [comment]
I attached the xl\workbook.xml file.
    On Friday, June 12, 2020, 11:34:14 AM CDT, Jan Källman <notifications@github.com> wrote:  
 
 


The workbook is a zip package , so rename the .xlsx file .zip. Then I would be interested in the xl\workbook.xml inside the package that contains the list of worksheets.

**Comment by JanKallman** [comment]
I can't see it here. I think you have to attach it to the pull request directly on github

**Pull request merged**
