### PR TITLE
fixed issue 766 SUM function had calculation precision problems, beca…

### PR DESCRIPTION
**Pull request by ihorbach**
…use using double

### CODE REVIEW

**Comment by swmal** [comment]
Hello,
we understand that this can cause some annoying problems in some cases, but to change the return value from the SUM function could potentially break other EPPlus users code if they are casting the calculated result to a double. Therefore it is something we only could do at the release of a new major function. We will eventually try to find a way around this that is more similar to Excel's, which  (as we have understood it) would be to keep the 64-bit double as the numeric datatype but round it to 15 significant figures.

**Comment by KseniaKaras** [comment]
Hello,
as far as I can see, this update doesn't actually change the return value of the SUM function. And the data type, that is exactly specified in the returned CompileResult, is Decimal, not Double. The other point as well is that this update doesn't degrade the calculation result, but makes it more precise. 
As for me it makes more sense to use decimal in calculations to provide users with more precise result. And speaking of those who cast the calculated results to double after the calculation - due to my experience with doubles and decimals, if doubles are successfully used in system, this system doesn't require accuracy, so the possible value changes after casting to double might be not a big deal.

**Comment by swmal** [comment]
We will adress this in the next major version of EPPlus (v7) by implementing the KahanSum algorithm, see this commit: https://github.com/EPPlusSoftware/EPPlus/commit/446755e9de10f5e88acb0f91e86fe30299c08654

**Comment by KseniaKaras** [comment]
Could you please tell, when we can expect the next major version of EPPlus?

**Comment by swmal** [comment]
@KseniaKaras EPPlus 7 is currently released as a preview on Nuget (make sure to include pre-releases in the feed). We hope to release the beta version in a couple of weeks and the first stable version in Q4.

The beta version will be the first version to implement KahanSum.

See these two wiki pages for more details:

https://github.com/EPPlusSoftware/EPPlus/wiki/EPPlus-7-Preview
https://github.com/EPPlusSoftware/EPPlus/wiki/Breaking-Changes-in-EPPlus-7

**Comment by swmal** [comment]
Closing this now after yesterdays discussion.

**Pull request closed without merging**
